[package]
name = "rktrl"
version = "0.1.0"
authors = ["Zoltán Nagy <abesto@abesto.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.7"
specs = "0.16.1"
specs-derive = "0.4.1"
serde = { version = "1.0.104", features = ["derive"] }
shred-derive = "0.6.2"
serde_json = "1.0.48"