[package]
name = "rktrl"
version = "0.1.0"
authors = ["Zoltán Nagy <abesto@abesto.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = { version = "0.8.1", features = ["serde"] }
serde = { version = "1.0.112", features = ["derive"] }
serde_json = "1.0.55"
auto_ops = "0.1.0"
newtype_derive = "0.1.6"
macro-attr = "0.2.0"
smallvec = "1.4.0"
strum = "0.18.0"
strum_macros = "0.18.0"
rand = "0.7.3"
shipyard = { git = "https://github.com/abesto/shipyard", branch = "more-components", features = ["non_send", "non_sync"] }
shrev = "1.1.1"
